In [7]:
import csv
import gspread
from oauth2client.service_account import ServiceAccountCredentials
scope = ['https://spreadsheets.google.com/feeds']
document_key = "13bsf7rP9ubfBSX7-hK3QayZIaUkTxrXaOZqGsfLjWX4"
credentials = ServiceAccountCredentials.from_json_keyfile_name('../../../../../SheetsBot-32718db5596a.json', scope)
csvfile = "output.csv"
gc = gspread.authorize(credentials)
wks = gc.open_by_key(document_key)
worksheet = wks.worksheet("Form Responses 1")
list_of_lists = worksheet.get_all_values()
with open(csvfile, "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    writer.writerows(list_of_lists)

import pandas as pd
output = pd.read_csv(csvfile)
output[:20]

,Timestamp,Project Name,Your Name,Your Supervisor
0,9/1/2016 1:02:56,Penny Pincher,Peter Gibbons,Bill Lumbergh
1,8/31/2016 21:27:04,Penny Pincher,Michael Bolton,Bill Lumbergh
2,8/31/2016 21:27:24,Penny Pincher,Samir Nagheenanajar,Bill Lumbergh
3,9/13/2016 0:26:03,Testing Your Python,Some Guy,Another Dude
4,9/13/2016 0:52:19,Another,Test,Will this work?
5,9/13/2016 1:49:45,And,The,Last
6,9/15/2016 14:53:04,Cool Project,Harrison Lebov,David Colarusso
7,9/15/2016 15:40:41,Argos Remembers,Anthony Davis,Anthony Michael Davis
8,1/19/2017 23:56:43,Lawyerist TPS reports,Greg Claesses,Odin
9,2/7/2017 11:11:00,Cool Project 2.0,Sol,Sam
10,2/9/2017 2:12:29,Coding,Tony,Jesse
11,2/9/2017 2:13:18,dd,dd,22
12,2/9/2017 2:13:24,bb,ed,ee
13,4/11/2017 17:38:06,Wow,Thank,You!
14,7/10/2017 8:36:59,Test Automation,Namer,Sup